select directory_id from ftp_mc_dirs where description in (
'DC Payment Feedback',
'DDI Request Extract Upload',
'DDI Extract Return Feedback',
'DD Payment Extract Upload',
'DD Payment Feedback',
'Amendments and Cancellations',
'DD Indemnity Claims',
'Reimbursement_Partner',
'CC Payment Feedback',
'CC Payment Extract Upload',
'PaymentCardEOD',
'Capita_FTP_CardUpdaterService_Result',
'CardUpdaterService_ReportUpload',
'FTPMC-MED-CI',
'Contravention Candidates To sFTP server',
'Collection DRA Upload BristowAndSutor',
'Collection DRA Download',
'Collection DRA Upload JBW',
'Collection DRA Upload Marstons',
'Reimbursement_Partner',
'Request_Statements_CCAutoPay',
'Request_Statements_FleetAutoPay',
'Request_Statements_Reimbursements',
'CardUpdaterService_Report',
'Collection DRA Extract',
'Collection DRA BristowAndSutor Download from DB',
'Collection DRA JBW Download from DB',
'Collection DRA Marstons Download from DB',
'Consolidated Receipt',
'PDF_Statement'
) order by 1;
